version: 0.0
os: linux
files:
  - source: /
    destination: /hosting/www/crm_school_backend
hooks:
  BeforeInstall:
    - location: scripts/prepare.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/build.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/startservices.sh
      timeout: 3600
      runas: root
  ApplicationStop:
    - location: scripts/stopservices.sh
      timeout: 3600
      runas: root
  ValidateService:
   - location: scripts/validateservices.sh